import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { getSerats } from ":networks/serats";
import styles from "../styles/Home.module.css";

export default function Home({ serats }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {serats.map((serat) => (
            <Link href={`/serats/${serat.id}`} key={serat.id}>
              <a className={styles.card}>
                <h2>{serat.title} &rarr;</h2>
                <p>{serat.description}</p>
              </a>
            </Link>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const { serats } = await getSerats();

  return {
    props: {
      serats,
    },
  };
}
