import Head from "next/head";
import { MainLayout } from ":layouts";
import { listSerats } from ":networks";
import SeratCard from ":components/SeratCard";
import styles from "../styles/Home.module.css";

export default function Home({ serats }) {
  return (
    <MainLayout>
      <Head>
        <title>Kasusastran</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles["Home-Hero"]}>
        <h1 className={styles["Home-Title"]}>
          <a href="https://nextjs.org">Kasusastran</a>
        </h1>

        <p className={styles["Home-Description"]}>
          Get started by editing{" "}
          <code className={styles["Home-Code"]}>pages/index.js</code>
        </p>
      </section>

      <section className={styles["Home-Grid"]}>
        {serats.map(({ id, title, description, thumbnail_image_url }) => (
          <SeratCard
            className={styles["Home-GridItem"]}
            key={id}
            href={"/serats/" + id}
            imgSrc={thumbnail_image_url}
            imgAlt={title}
          >
            <h1>{title}</h1>
            <p>{description}</p>
          </SeratCard>
        ))}
      </section>
    </MainLayout>
  );
}

export async function getServerSideProps() {
  const { serats } = await listSerats();

  return {
    props: {
      serats,
    },
  };
}
